import os

import discord
from discord import app_commands
from dotenv import load_dotenv

from database import initialize_database
from api import api


# Load environment variables
load_dotenv()

TOKEN = os.getenv("DISCORD_TOKEN")

if not TOKEN:
    raise RuntimeError(
        "DISCORD_TOKEN is not set. "
        "Add it to your environment variables."
    )


# Initialize the database
initialize_database()


class ComVerify(discord.Client):
    def __init__(self):
        intents = discord.Intents.default()

        super().__init__(
            intents=intents
        )

        self.tree = app_commands.CommandTree(self)

    async def setup_hook(self):
        await self.tree.sync()

    async def on_ready(self):
        print("--------------------------------")
        print("        ComVerify Online")
        print("--------------------------------")
        print(f"Bot: {self.user}")
        print(f"Bot ID: {self.user.id}")
        print(f"Servers: {len(self.guilds)}")
        print("Slash commands synced.")
        print("--------------------------------")


bot = ComVerify()


@bot.tree.command(
    name="ping",
    description="Check if ComVerify is online."
)
async def ping(interaction: discord.Interaction):
    latency = round(bot.latency * 1000)

    await interaction.response.send_message(
        f"🏓 Pong! `{latency}ms`"
    )


@bot.tree.command(
    name="help",
    description="Show ComVerify's commands."
)
async def help_command(interaction: discord.Interaction):
    embed = discord.Embed(
        title="ComVerify",
        description=(
            "Community verification and recovery.\n\n"
            "ComVerify is currently being configured."
        ),
        color=discord.Color.blurple()
    )

    embed.add_field(
        name="Available Commands",
        value=(
            "`/ping` — Check if ComVerify is online.\n"
            "`/help` — Show this help menu.\n"
            "`/login` — Connect this server to ComVerify."
        ),
        inline=False
    )

    embed.set_footer(
        text="ComVerify"
    )

    await interaction.response.send_message(
        embed=embed,
        ephemeral=True
    )


@bot.tree.command(
    name="login",
    description="Connect this Discord server to a ComVerify project."
)
@app_commands.describe(
    project_key="The project key generated by the ComVerify dashboard."
)
async def login(
    interaction: discord.Interaction,
    project_key: str
):
    # Only allow users with administrator permissions
    # to link a server.
    if not interaction.user.guild_permissions.administrator:
        await interaction.response.send_message(
            "❌ You need Administrator permissions to link "
            "this server to ComVerify.",
            ephemeral=True
        )
        return

    await interaction.response.defer(
        ephemeral=True
    )

    guild = interaction.guild

    if guild is None:
        await interaction.followup.send(
            "❌ This command can only be used inside a server.",
            ephemeral=True
        )
        return

    try:
        status, result = await api.login_server(
            project_key=project_key,
            guild_id=str(guild.id),
            guild_name=guild.name,
            owner_id=str(interaction.user.id)
        )

    except Exception as error:
        print(f"Login API error: {error}")

        await interaction.followup.send(
            "❌ I couldn't contact the ComVerify dashboard. "
            "Please try again later.",
            ephemeral=True
        )
        return

    if status == 200 and result.get("success"):
        await interaction.followup.send(
            "✅ **Server connected!**\n\n"
            f"This server is now linked to the "
            f"**{result.get('project_name', 'ComVerify project')}** "
            "project.",
            ephemeral=True
        )

    elif status == 401:
        await interaction.followup.send(
            "❌ That project key is invalid or has expired.",
            ephemeral=True
        )

    elif status == 403:
        await interaction.followup.send(
            "❌ You don't have permission to use that project key.",
            ephemeral=True
        )

    elif status == 409:
        await interaction.followup.send(
            "❌ This server is already linked to a ComVerify project.",
            ephemeral=True
        )

    elif status == 429:
        await interaction.followup.send(
            "⏳ Too many login attempts. Please try again later.",
            ephemeral=True
        )

    else:
        await interaction.followup.send(
            "❌ The ComVerify dashboard rejected the login request.",
            ephemeral=True
        )


bot.run(TOKEN)
