import os

import discord
from discord import app_commands
from dotenv import load_dotenv

from database import initialize_database
from api import api
from backup import backup_command


load_dotenv()

TOKEN = os.getenv("DISCORD_TOKEN")

if not TOKEN:
    raise RuntimeError(
        "DISCORD_TOKEN is not set. "
        "Add it to your environment variables."
    )


# Initialize the database when the bot starts
initialize_database()


class ComVerify(discord.Client):
    def __init__(self):
        intents = discord.Intents.default()

        super().__init__(
            intents=intents
        )

        self.tree = app_commands.CommandTree(self)

    async def setup_hook(self):
        # Register slash commands with Discord
        await self.tree.sync()

    async def on_ready(self):
        print("--------------------------------")
        print("        ComVerify Online")
        print("--------------------------------")
        print(f"Bot: {self.user}")
        print(f"Bot ID: {self.user.id}")
        print(f"Servers: {len(self.guilds)}")
        print("Slash commands synced.")
        print("--------------------------------")


bot = ComVerify()


# -------------------------
# /ping
# -------------------------

@bot.tree.command(
    name="ping",
    description="Check if ComVerify is online."
)
async def ping(interaction: discord.Interaction):
    latency = round(bot.latency * 1000)

    await interaction.response.send_message(
        f"🏓 Pong! `{latency}ms`"
    )


# -------------------------
# /help
# -------------------------

@bot.tree.command(
    name="help",
    description="Show ComVerify's commands."
)
async def help_command(interaction: discord.Interaction):

    embed = discord.Embed(
        title="ComVerify",
        description=(
            "Community verification, member backup "
            "and server recovery."
        ),
        color=discord.Color.blurple()
    )

    embed.add_field(
        name="Getting Started",
        value=(
            "`/login` — Connect this server to a "
            "ComVerify project."
        ),
        inline=False
    )

    embed.add_field(
        name="Commands",
        value=(
            "`/ping` — Check bot latency\n"
            "`/help` — Show this menu\n"
            "`/login` — Connect your server\n"
            "`/backup` — Create a backup"
        ),
        inline=False
    )

    embed.set_footer(
        text="ComVerify"
    )

    await interaction.response.send_message(
        embed=embed,
        ephemeral=True
    )


# -------------------------
# /login
# -------------------------

@bot.tree.command(
    name="login",
    description="Connect this server to a ComVerify project."
)
@app_commands.describe(
    project_key=(
        "The project key generated by the "
        "ComVerify dashboard."
    )
)
async def login(
    interaction: discord.Interaction,
    project_key: str
):

    if not interaction.user.guild_permissions.administrator:
        await interaction.response.send_message(
            "❌ You need Administrator permissions "
            "to connect this server.",
            ephemeral=True
        )
        return

    if interaction.guild is None:
        await interaction.response.send_message(
            "❌ This command can only be used inside "
            "a Discord server.",
            ephemeral=True
        )
        return

    await interaction.response.defer(
        ephemeral=True
    )

    guild = interaction.guild

    try:
        status, result = await api.login_server(
            project_key=project_key,
            guild_id=str(guild.id),
            guild_name=guild.name,
            owner_id=str(interaction.user.id)
        )

    except Exception as error:
        print(f"Login API error: {error}")

        await interaction.followup.send(
            "❌ I couldn't connect to the "
            "ComVerify dashboard.",
            ephemeral=True
        )
        return

    if status == 200 and result.get("success"):

        project_name = result.get(
            "project_name",
            "ComVerify project"
        )

        await interaction.followup.send(
            "✅ **Server connected!**\n\n"
            f"This server is now linked to "
            f"**{project_name}**.",
            ephemeral=True
        )

        return

    if status == 401:
        message = (
            "❌ That project key is invalid "
            "or expired."
        )

    elif status == 403:
        message = (
            "❌ You don't have permission "
            "to use that project key."
        )

    elif status == 409:
        message = (
            "❌ This server is already "
            "linked to a project."
        )

    elif status == 429:
        message = (
            "⏳ Too many login attempts. "
            "Please try again later."
        )

    else:
        message = (
            "❌ The ComVerify dashboard "
            "rejected the login."
        )

    await interaction.followup.send(
        message,
        ephemeral=True
    )


# -------------------------
# /backup
# -------------------------

@bot.tree.command(
    name="backup",
    description="Create a ComVerify server backup."
)
async def backup(
    interaction: discord.Interaction
):
    await backup_command(interaction)


# -------------------------
# Start bot
# -------------------------

bot.run(TOKEN)
